### ISSUE TITLE
3.1. Citations

### ISSUE THREAD

**Issue by sautin1** [kotfind/1c-web2#2]
Привет! :)
Решение выглядит очень хорошо, но давай исправим несколько замечаний :)

1) CSS в одном файле с HTML -- а-яй-яй. :(
2) По заданию клиент должен посылать запрос по маршруту "/quote".
3) В сервере лучше заменить константу 10 на реальную длину списка:
`var random = Math.round(Math.random()*10);`

Также мне кажется, что переносы строк в database.txt были бы более читаемым разделителем. Но это не принципиально.

В остальном все круто, молодец! ;)

**Comment by kotfind** [comment]
Исправил

**Comment by sautin1** [comment]
Оставил тебе коммент к коммиту:
https://github.com/kotfind/1c-web2/commit/27c76e68fc57c9e0615011dcd78a28e499e95285

**Comment by sautin1** [comment]
И еще один :)

**Comment by sautin1** [comment]
Принято!
