### ISSUE TITLE
5.7.1. Logical Element

### ISSUE THREAD

**Issue by sautin1** [kotfind/1c-web2#5]
1. А зачем делать приведение логических переменных к числам и потом работать с ними, если можно просто сделать так: `first && second`? :)
2. Собери стили по одному селектору вместе.

**Comment by kotfind** [comment]
Какие стили? Там вроде всё собрано.

**Comment by sautin1** [comment]
Селектор p указан дважды.

**Comment by sautin1** [comment]
Принято. :)
